Update to 3.4.0
AnacondaRecipes/constructor-feedstock pull request #7
Opened 2023-01-17 16:26 UTC by dbast

2023-01-17 16:27 UTC, anaconda-pkg-build commented
<details><summary>Linter check found the following problems:</summary>
The following problems have been found:

WARNING: /tmp/abs_c3vupa4xzt/clone/recipe/meta.yaml:65: missing_license_url: The recipe is missing a license_url
WARNING: /tmp/abs_c3vupa4xzt/clone/recipe/meta.yaml:65: missing_doc_source_url: The recipe is missing a doc_source_url
Warnings were found

</details>

2023-01-17 17:16 UTC, pseudoyim approved these changes

2023-01-17 17:34 UTC, jaimergp requested changes
I think 3.4.0 is broken by https://github.com/conda/constructor/issues/576

Investigating in https://github.com/conda/constructor/pull/614

2023-01-17 22:36 UTC, varlackc approved these changes
LGTM

2023-01-18 10:50 UTC, skupr-anaconda commented on recipe/meta.yaml
>    script: "{{ PYTHON }} -m pip install . -vv"
Double quotes `"` can be removed. The flag `--no-deps` can be added

2023-01-18 10:50 UTC, skupr-anaconda commented on recipe/meta.yaml
>      - ruamel_yaml >=0.11.14,<0.16
Does `ruamel_yaml` still require `>=0.11.14,<0.16 ` or it can work with the latest version too?

2023-01-18 10:50 UTC, skupr-anaconda commented on recipe/meta.yaml
>  requirements:
`build` with `m2-patch `and `patch` aren't needed anymore if we remove `patches`

2023-01-18 20:23 UTC, dbast commented on recipe/meta.yaml
>      - ruamel_yaml >=0.11.14,<0.16
Not sure, thats how it is tested in https://github.com/conda/constructor/blob/main/conda.recipe/meta.yaml

2023-01-18 20:25 UTC, dbast commented on recipe/meta.yaml
> +  license_url: https://github.com/conda/constructor/blob/{{ version }}/LICENSE.txt
done

2023-01-18 20:25 UTC, dbast commented on recipe/meta.yaml
> +  doc_source_url: https://github.com/conda/constructor/tree/{{ version }}/docs
done

2023-01-18 20:25 UTC, anaconda-pkg-build commented
<details><summary>Linter check found the following problems:</summary>
The following problems have been found:

WARNING: /tmp/abs_e5e7jrepy0/clone/recipe/meta.yaml:62: missing_doc_source_url: The recipe is missing a doc_source_url
WARNING: /tmp/abs_e5e7jrepy0/clone/recipe/meta.yaml:62: missing_license_url: The recipe is missing a license_url
Warnings were found

</details>

2023-01-18 20:26 UTC, dbast commented on recipe/meta.yaml
>    script: "{{ PYTHON }} -m pip install . -vv"
done

2023-01-18 20:26 UTC, dbast commented on recipe/meta.yaml
>  requirements:
done

2023-01-19 09:10 UTC, skupr-anaconda commented on recipe/meta.yaml
>      - pillow >=3.1
I think it can be removed from `test/requires` as we already have it in `run`

2023-01-19 09:10 UTC, skupr-anaconda commented on recipe/meta.yaml
>      - examples
As we don't run the test command `python scripts/run_examples.py  # [not win]` we can remove `scripts` and `examples` from `source_files`. It will reduce the size of the artifacts.

2023-01-19 09:10 UTC, skupr-anaconda commented on recipe/meta.yaml
> +    # - python scripts/run_examples.py  # [not win]
This script and a comment are redundant

2023-01-20 16:54 UTC, dbast commented on recipe/meta.yaml
> +    # - python scripts/run_examples.py  # [not win]
Lets keep that... it shows how to run the extensive test-suite... which currently won't run due to missing signing tools.

2023-01-20 16:55 UTC, dbast commented on recipe/meta.yaml
>      - examples
lets keep it as the recipe in the constructor repo contains those and this also does not influence any size of artifacts on the build system.

2023-01-20 16:59 UTC, merged

2023-01-20 16:59 UTC, anaconda-pkg-build commented
<details><summary>Linter check found the following problems:</summary>
The following problems have been found:

WARNING: /tmp/abs_43xnocc5oz/clone/recipe/meta.yaml:62: missing_license_url: The recipe is missing a license_url
WARNING: /tmp/abs_43xnocc5oz/clone/recipe/meta.yaml:62: missing_doc_source_url: The recipe is missing a doc_source_url
Warnings were found

</details>